name: Build
on: [ push, pull_request ]

jobs:
  build:
    name: On ${{ matrix.os }} with Go ${{ matrix.go_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go_version: [ 1.15 ]
        os: [ ubuntu-latest, windows-latest, macOS-latest ]
    steps:
      - name: Set up Go ${{ matrix.go_version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go_version }}
        id: go
      - name: Check out code
        uses: actions/checkout@v2
      - name: Go mod verify
        run: go mod verify
      - name: Go vet normally
        run: go vet ./...
      - name: Go build
        run: go build ./...
      - name: Binary
        run: go build -o bin/protoc-gen-redact .
